name: OpenWrt RootFS Extractor

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install tools
        run: |
          sudo apt update

          sudo apt install -y \
            wget \
            curl \
            git \
            file \
            rsync \
            p7zip-full \
            unzip \
            xz-utils \
            gzip \
            bzip2 \
            tar \
            binwalk \
            squashfs-tools \
            sasquatch

      # Download firmware
      - name: Download firmware
        run: |
          wget -O firmware.bin \
          "https://drive.usercontent.google.com/uc?id=1mxqnnH5r3YLlU4on0YMZVTZSrre72C3o&export=download"

      # Show firmware info
      - name: Show firmware info
        run: |
          ls -lah
          file firmware.bin

      # Extract firmware
      - name: Extract firmware
        run: |
          sudo binwalk \
            --run-as=root \
            -Me \
            firmware.bin

      # Fix permissions
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER .
          chmod -R u+rwX .

      # Find squashfs-root
      - name: Find squashfs-root
        run: |
          echo "===== FIND ROOTFS ====="

          find . -type d -name "squashfs-root"

      # Prepare output
      - name: Prepare rootfs
        run: |
          rm -rf files
          mkdir -p files

          ROOTFS_DIR=$(find . -type d -name "squashfs-root" | head -n 1)

          if [ -z "$ROOTFS_DIR" ]; then
            echo "ERROR: squashfs-root not found"
            exit 1
          fi

          echo "FOUND ROOTFS:"
          echo "$ROOTFS_DIR"

          rsync -a \
            --delete \
            --exclude dev \
            --exclude proc \
            --exclude sys \
            --exclude tmp \
            --exclude overlay \
            "$ROOTFS_DIR"/ \
            files/

      # Show extracted files
      - name: Show rootfs
        run: |
          echo "===== ROOTFS ====="

          du -sh rootfs

          find files | head -200

      # Create archive
      - name: Pack rootfs
        run: |
          tar -czf rootfs.tar.gz rootfs

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-rootfs
          path: |
            rootfs
            rootfs.tar.gz

      # Commit extracted rootfs
      - name: Commit rootfs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add files

          git commit -m "Auto extract firmware files" || echo "No changes"

          git push
